apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-health" (include "keydb.fullname" . ) }}
  labels:
    {{ include "keydb.labels" . | nindent 4 }}
data:
  ping_readiness_local.sh: |-
    #!/bin/bash

    script_dir="$(dirname "$0")"
    exit_status=0

{{- if ((.Values.scripts).cleanup).enabled }}

    "$script_dir/cleanup_local_data.sh" || exit_status=$?
{{- end }}

    [[ -n "$REDIS_PASSWORD" ]] && export REDISCLI_AUTH="$REDIS_PASSWORD"
    response=$(
      timeout -s 3 $1 \
      keydb-cli \
        -h localhost \
        -p $REDIS_PORT \
        ping
    )
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
    exit $exit_status

  ping_liveness_local.sh: |-
    #!/bin/bash

    script_dir="$(dirname "$0")"
    exit_status=0

    [[ -n "$REDIS_PASSWORD" ]] && export REDISCLI_AUTH="$REDIS_PASSWORD"
    response=$(
      timeout -s 3 $1 \
      keydb-cli \
        -h localhost \
        -p $REDIS_PORT \
        ping
    )
    if [ "$response" != "PONG" ] && [ "$response" != "LOADING Redis is loading the dataset in memory" ]; then
      echo "$response"
      exit 1
    fi
    exit $exit_status

{{- if ((.Values.scripts).cleanup).enabled }}

  cleanup_local_data.sh: |-
    #!/bin/bash

    exit_status=0

    find /data/ -type f -name temp-*.rdb  -mmin +{{ default 90  ((.Values.scripts).cleanup).minutes}} -delete

    exit $exit_status
{{- end }}
