apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "keydb.fullname" . }}
  labels:
{{ include "keydb.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.nodes }}
  serviceName: {{ template "keydb.fullname" . }}
  selector:
    matchLabels:
{{ include "keydb.selectorLabels" . | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret-utils: {{ include (print $.Template.BasePath "/secret-utils.yaml") . | sha256sum }}
        {{- if .Values.exporter.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "{{ .Values.exporter.scrapePath }}"
        prometheus.io/port: "{{ .Values.exporter.port }}"
        {{- end }}
      labels:
{{ include "keydb.labels" . | indent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ template "keydb.name" . }}
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
        {{- if .Values.additionalAffinities }}
{{ toYaml .Values.additionalAffinities | indent 8 }}
        {{- end }}
      containers:
      - name: keydb
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - /utils/server.sh
        ports:
        - name: keydb
          containerPort: 6379
          protocol: TCP
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: keydb-data
          mountPath: /data
        - name: utils
          mountPath: /utils
          readOnly: true
{{- if .Values.exporter.enabled }}
      - name: redis-exporter
        image: {{ .Values.exporter.image }}
        imagePullPolicy: {{ .Values.exporter.pullPolicy }}
        args:
        {{- range $key, $value := .Values.exporter.extraArgs }}
        - --{{ $key }}={{ $value }}
        {{- end }}
        env:
        - name: REDIS_ADDR
          value: redis://localhost:6379
        {{- if .Values.password }}
        - name: REDIS_PASSWORD
          value: "{{ .Values.password }}"
        {{- end }}
        {{- if .Values.exporter.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.exporter.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.exporter.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.exporter.readinessProbe | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.exporter.resources | indent 10 }}
        ports:
        - name: redis-exporter
          containerPort: {{ .Values.exporter.port }}
{{- end }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      volumes:
      - name: utils
        secret:
          secretName: {{ template "keydb.fullname" . }}-utils
          defaultMode: 0700
          items:
          - key: server.sh
            path: server.sh
      {{- if not .Values.persistentVolume.enabled }}
      - name: keydb-data
        emptyDir: {}
      {{- end }}
  {{- if .Values.persistentVolume.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: keydb-data
      annotations:
      {{- if .Values.persistentVolume.annotations }}
{{ toYaml .Values.persistentVolume.annotations | indent 8 }}
      {{- end }}
      labels:
    spec:
      accessModes:
{{ toYaml .Values.persistentVolume.accessModes | indent 8 }}
      resources:
        requests:
          storage: {{ .Values.persistentVolume.size }}
      {{- if .Values.persistentVolume.storageClass }}
      {{- if (eq "-" .Values.persistentVolume.storageClass) }}
      storageClassName: ""
      {{ else }}
      storageClassName: {{ .Values.persistentVolume.storageClass }}
      {{- end }}
      {{- end }}
  {{- end }}
