# Headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keydb.fullname" . }}-headless
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: {{ .Values.port | int }}
    protocol: TCP
    targetPort: keydb
  selector:
    {{- include "keydb.selectorLabels" . | nindent 4 }}
