apiVersion: v1
kind: Service
metadata:
  name: {{ include "keydb.fullname" . }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: server
    port: {{ .Values.port | int }}
    protocol: TCP
    targetPort: keydb
  - name: redis-exporter
    port: {{ .Values.exporter.port | int }}
    protocol: TCP
    targetPort: redis-exporter
  selector:
    {{- include "keydb.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
