# Headless service for proper name resolution
apiVersion: v1
kind: Service
metadata:
  name: {{ template "keydb.fullname" . }}
  labels:
{{ include "keydb.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: {{ .Values.port | int }}
    protocol: TCP
    targetPort: keydb
  - name: redis-exporter
    port: {{ .Values.exporter.port | int }}
    protocol: TCP
    targetPort: redis-exporter
  selector:
{{ include "keydb.selectorLabels" . | indent 4 }}
