name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:

  helm-chart:
    runs-on:
    - self-hosted
    - kaas

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Build Chart
      run: helm package ./keydb/ --destination ./.deploy/

    - name: Notify failure
      if: failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} PR build. Please check [here](${{ github.event.pull_request.html_url }}/checks)."
      run: |
        send-to-mattermost
